version: "2.2"
services:
  
  blazegraph-geonames:
#    container_name: blazegraph-vision
    image: ${BLAZEGRAPH_IMAGE}
    restart: always
    mem_limit: ${BLAZEGRAPH_MEMORY}
    mem_reservation: ${BLAZEGRAPH_MEMORY}
    environment:
      JAVA_OPTS: ${BLAZEGRAPH_JAVA_OPTS}
    volumes:
     - ./blazegraph/:/blazegraph-data
    ports:
     - "10085:8080"
    logging:
     driver: json-file
     options:
      max-size: "200k"
      max-file: "10"

networks:
  default:
    external:
      name: nginx-docker-gen
